apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: foo
spec:
  selector:
    matchLabels:
      run: dotnet-app
  replicas: 1
  template:
    metadata:
      labels:
        run: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: ec2-34-245-129-27.eu-west-1.compute.amazonaws.com:5000/dotnetcore #mcr.microsoft.com/dotnet/core/samples:aspnetapp #nginx
        resources:
          limits:
            memory: 512Mi
            cpu: 2
          requests:
            memory: 256Mi
            cpu: 1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: foo
  labels:
    run: dotnet-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: dotnet-app


---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-core-hpa
  namespace: foo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnet-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
